<a href="https://colab.research.google.com/github/aayush-kushwaha/Aayush-git/blob/master/Data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values #excluding the last column(don't have feature dataset so we need to remove[data containing number]) as -1 is used and ":" excludes the last     
Y = dataset.iloc[:, -1].values #selects the last column as semicolon is not used

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


##Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer #SimpleImputer is a class
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #"SimpleImputer()" inside paranthesis is an object #.nan means missing value
imputer.fit(X[:, 1:3]) 
#(row, columns) format
X[:, 1:3] = imputer.transform(X[:, 1:3]) 
# "X[:, 1:3]" has been assigned to replace the old blank value with the new one!!!! "imputer.transform(X[:, 1:3])" Adds values to the missing salary and age

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
from sklearn.compose import ColumnTransformer # ColumnTransformer is a class
from sklearn.preprocessing import OneHotEncoder # OneHotEncoder is a class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
#encoder helps to transform data into numerical value and "[0]" here means country column whereas in REMAINDER we specify which value shouldn't be transformed
#remainder = "passthrough" helps to keep the column that won't be applied some transformation or won't be OneHotEncoded i.e. Age & Salary... TO preserve matrix of feature
X = np.array(ct.fit_transform(X))
#In order to train ML model 'train' function will expect it to be in numpy(the matrix of feature).
#So we force the output of this transfomration to be a numpy array

In [8]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder #LabelEncoder is a class which helps to change the String value to 0 or 1 
le = LabelEncoder()
Y = le.fit_transform(Y)

In [10]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size = 0.2, random_state = 1) # We used "random_state = 1" to get same split 
#We need more observation in training set so 80% will be enough for training set and 20% will be for test set as a result "test_size = 0.2" has been written

In [12]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(Y_test)

[0 1]


## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler #Used for Standardisation feature scaling
sc = StandardScaler() #It gets the mean and standard deviation of X and automatically applies the formula of X(standardisation)
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) # 'fit' will only compute mean and standard deviation of the all values (Age, Salary)
# And transform applies the formula and calcualate the value of X(Standardisation)
#X_train[:, 3:] means => X_train[all rows, and column from 3rd index to the end]
X_test[:, 3:] = sc.transform(X_test[:, 3:]) # We didn't use 'sc.fit_transform' here because this is a test set and we need to avoid data leakage
#Test set should remain confidential and shouldn't be exposed and it is new data for machine

In [17]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [18]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
